"""Compute each BASIC array's data offset from the first array's data.

MSX BASIC array entry: type(1) name(2) length(2) ndims(1) dims(2*ndims) data.
So a 1-D integer array costs 8 header bytes, a 2-D one 10.  Arrays are laid out
in the order DIM executes, which lets the Z80 derive every pointer from one base.
"""
import re, sys, os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, 'tools'))
import build as B


def offsets(drop):
    src = open(os.path.join(ROOT, 'src', 'IRONCLAD.BAS'), encoding='latin-1', newline='')
    lines = {}
    for l in src.read().replace('\x1a', '').replace('\r', '').split('\n'):
        if l.strip():
            n, _, b = l.partition(' ')
            lines[int(n)] = b
    order, off, first = [], {}, None
    pos = 0
    for n in sorted(lines):
        if B.in_ranges(n, drop) or lines[n].startswith('REM'):
            continue
        for m in re.finditer(r'DIM([^:]*)', lines[n]):
            for a in re.finditer(r'([A-Z][A-Z0-9]?)(\$?)\((\d+)(?:,(\d+))?\)', m.group(1)):
                name, sdollar, d1, d2 = a.group(1), a.group(2), int(a.group(3)), a.group(4)
                dims = 1 if d2 is None else 2
                entries = (d1 + 1) * ((int(d2) + 1) if d2 else 1)
                esize = 3 if sdollar else 2
                header = 6 + 2 * dims          # type+name(2)+length(2)+ndims + dims          # type+name+length+ndims + dims
                if first is None:
                    first = name
                    off[name] = 0
                    pos = entries * esize
                else:
                    pos += header
                    off[name] = pos
                    pos += entries * esize
                order.append(name)
    return first, off, order


if __name__ == '__main__':
    mode = sys.argv[1] if len(sys.argv) > 1 else 'salvo'
    drop = B.STD_ONLY + (B.SALVO_ONLY if mode == 'sp' else B.SP_ONLY)
    first, off, order = offsets(drop)
    want = ['MG', 'CC', 'OS', 'SZ', 'PH', 'TX', 'TY', 'HK', 'BZ', 'PM']
    print(f'; array data offsets from {first}(0) for the {mode} build,'
          f' generated by tools/aryoffs.py {mode}')
    for w in want:
        print(f'o{w:<3} equ {off[w]}')
    print(';', ' '.join(order))
